### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by MarzaElise** [Darren-project/Discord-scam-links#6]
https://github.com/mickeydarrenlau/Discord-scam-links/blob/e0d951d270c873570a3b12e6ee3d46d6ff6b8cad/nitroscamlinks.txt#L4820

Why the fuck is my ko-fi link in there. Do you like, not check what a PR adds to the repo?

**Comment by MarzaElise** [comment]
I suggest not blindly accepting and merging PRs

**Comment by darrenwjlau** [comment]
Fixed
